### PR TITLE
Contribution by danielmichaels

### PR DESCRIPTION
**Pull request by danielmichaels**
Pull request for issue #11

Thanks!

### CODE REVIEW

**Comment by shreyateeza** [comment]
Hey @danielmichaels ! Your PR Comment has been updated. 
Please apply for [Hacktoberfest](https://hacktoberfest.digitalocean.com). It's a fest celebrating open source where you get to win a free hacktoberfest t-shirt! Know more about it at the link itself.

**Comment by danielmichaels** [comment]
Thanks @shreyateeza  
Great work here!

**Comment by shreyateeza** [comment]
Closed PRs won't count for hacktoberfest. This needs to be reopened!
Once opened, it will merged soon.

**Comment by shreyateeza** [comment]
Hey! I really wanna know about your blog! :+1:

**Pull request merged**
